### ISSUE TITLE
Support for iOS SPM?

### ISSUE THREAD

**Issue by murillotomas** [opentok/opentok-ios-sdk-samples#258]
Hello, I would like to know when you will be giving support for iOS Swift Package Manager. It would make it much simpler to update than just throwing the updated version of "OpenTok.framework" into the project.

**Comment by tumata** [comment]
https://github.com/opentok/opentok-ios-sdk-samples/tree/main/Basic-Video-Chat-XCFramework

**Comment by v-kpheng** [comment]
@murillotomas, apologies for the belated reply.

No, there are no plans to support SPM currently.

**Comment by DogeWowzie** [comment]
> @murillotomas, apologies for the belated reply.
> 
> No, there are no plans to support SPM currently.

It is not a big deal to create a swift package from `OpenTok.xcframework`. I did it by myself in five minutes of time while many paying customers have actually been waiting since 2020 for this to happen.

https://github.com/opentok/opentok-ios-sdk-samples-swift/issues/130#issuecomment-1250127285

Only thing what is missing in the binary framework is support for M1 simulators above iOS 13.7
